services:

  database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres        
    ports:
        - "5432:5432"
    container_name: "postgres"

  dotnet:
    build:
      context: ./dotnet
    ports:
      - "5001:8080"

  flask:
    build:
      context: ./python
    ports:
      - "5000:5000"
